namespace: app

# Helm で Secret を作成するかどうか（.env.secret を使う場合は false）
createSecret: true

image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

auth:
  username: appuser
  password: change-me-strong
  database: todos

persistence:
  size: 10Gi
  storageClassName: "local-path"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

networkPolicy:
  enabled: true
  allowFromAppLabel: api
