namespace: app

image:
  repository: docker.io/subaru88/home-kube
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 3000

env:
  NODE_ENV: development
  ALLOWED_ORIGINS: "http://localhost:5173,http://localhost:3001"
  JWT_SECRET: "local-dev-secret-change-me"

postgres:
  useSecret: true
  secretName: postgres-secret
  host: postgres.app.svc.cluster.local
  port: "5432"

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

imagePullSecrets: []
