namespace: app

# ローカル環境では Helm で Secret を作成（開発の利便性）
createSecret: true

image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

auth:
  username: localuser
  password: localpass
  database: todos

persistence:
  size: 5Gi
  storageClassName: "local-path"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

networkPolicy:
  enabled: false  # ローカルはデバッグしやすいよう無効
