apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Generate secrets from local files (not in Git)
secretGenerator:
  - name: postgres-secret
    envs:
      - .env.secret

images:
  - name: IMAGE_PLACEHOLDER
    newName: docker.io/subaru88/home-kube
    newTag: latest

patches:
  - path: ingress-patch.yaml
  - path: imagepullsecret-patch.yaml
