apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

# Generate secrets from local files (not in Git)
secretGenerator:
  - name: postgres-secret
    envs:
      - .env.secret
  - name: regcred
    files:
      - .dockerconfigjson=./docker-config.json
    type: kubernetes.io/dockerconfigjson

# baseのIMAGE_PLACEHOLDERを更新
images:
  - name: IMAGE_PLACEHOLDER
    newName: docker.io/subaru88/home-kube
    newTag: 0.1.3

patches:
  - imagepullsecret.patch.yaml
