apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Generate secrets from local files (not in Git)
secretGenerator:
  - name: postgres-secret
    envs:
      - .env.secret

images:
  - name: IMAGE_PLACEHOLDER
    newName: docker.io/subaru88/home-kube
    newTag: 0.1.3

patches:
  - path: deployment-patch.yaml

replicas:
  - name: todo-api
    count: 2
