namespace: app

image:
  repository: docker.io/subaru88/home-kube
  tag: "v1.0.0"  # 本番は固定バージョン
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 3000

env:
  NODE_ENV: production
  ALLOWED_ORIGINS: "https://app.octomblog.com"
  # JWT_SECRET は .env.secret から postgres-secret として注入されます

postgres:
  useSecret: true
  secretName: postgres-secret
  host: postgres.app.svc.cluster.local
  port: "5432"
  # JWT_SECRET も同じ postgres-secret から注入されます
  injectJwtSecret: true

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

imagePullSecrets: []
