namespace: app

image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

auth:
  # 注意: これらの値は .env.secret が存在する場合は上書きされます
  # 実際の認証情報は deployment/environments/prod/.env.secret に設定してください
  # .env.secret がない場合のみ、以下のデフォルト値が使用されます
  username: postgres
  password: postgres
  database: todos

persistence:
  size: 20Gi
  storageClassName: "local-path"

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "2000m"
    memory: "2Gi"

networkPolicy:
  enabled: true  # 本番は必須
  allowFromAppLabel: api
